"""empty message

Revision ID: 627eaa7a8d73
Revises: 
Create Date: 2022-06-08 17:26:36.557801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '627eaa7a8d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college')
    op.drop_index('stu_num', table_name='students')
    op.drop_table('students')
    op.drop_index('tea_num', table_name='teachers')
    op.drop_table('teachers')
    op.drop_table('contacts')
    op.drop_table('class_card')
    op.drop_table('physical_examination')
    op.drop_table('jrxy_info')
    op.drop_index('cno', table_name='course')
    op.drop_table('course')
    op.drop_table('class')
    op.drop_index('name', table_name='major')
    op.drop_table('major')
    op.drop_table('shop_address')
    op.drop_table('dormitory')
    op.drop_table('mark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mark',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('stu_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='学生id'),
    sa.Column('cno_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='课程id'),
    sa.Column('score', mysql.DECIMAL(precision=4, scale=2), nullable=True, comment='成绩'),
    sa.Column('upadted_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('created_time', mysql.DATETIME(), nullable=True, comment='插入时间'),
    sa.ForeignKeyConstraint(['cno_id'], ['course.id'], name='mark_ibfk_2', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stu_id'], ['students.uid'], name='mark_ibfk_1', onupdate='RESTRICT', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('dormitory',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('region', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=True, comment='区域,天河校区西区、天河校区东区'),
    sa.Column('dorm_name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=True, comment='宿舍楼名'),
    sa.Column('dorm_no', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=3), nullable=True, comment='宿舍号'),
    sa.Column('dorm_fee', mysql.FLOAT(precision=10, scale=2), nullable=True, comment='宿舍费'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('shop_address',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), nullable=True, comment='姓名'),
    sa.Column('nickname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=10), nullable=True, comment='昵称'),
    sa.Column('phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=11), nullable=True, comment='手机号码'),
    sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='详细地址'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='状态，1使用 0不使用'),
    sa.Column('created_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('major',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=15), nullable=True, comment='专业名称'),
    sa.Column('college', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='学院'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('name', 'major', ['name'], unique=False)
    op.create_table('class',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=True, comment='班级名称'),
    sa.Column('major', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='专业'),
    sa.Column('headmaster', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=8), nullable=True, comment='班主任'),
    sa.Column('instructor', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=8), nullable=True, comment='辅导员'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('course',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='id'),
    sa.Column('cno', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=8), nullable=False, comment='课程编号'),
    sa.Column('cname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=False, comment='课程名称'),
    sa.Column('credit', mysql.TINYINT(display_width=2), autoincrement=False, nullable=True, comment='学分'),
    sa.Column('cours', mysql.TINYINT(display_width=2), autoincrement=False, nullable=True, comment='学时'),
    sa.Column('attribute', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=5), nullable=True, comment='课程属性'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('cno', 'course', ['cno'], unique=False)
    op.create_table('jrxy_info',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='id'),
    sa.Column('schoolname', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True, comment='学校名称'),
    sa.Column('username', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=False, comment='用户名'),
    sa.Column('password', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=False, comment='密码'),
    sa.Column('address', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=100), nullable=True, comment='定位地址'),
    sa.Column('status', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True, comment='状态 1启用 0弃用'),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=50), nullable=True, comment='用来接收消息'),
    sa.Column('created_time', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('physical_examination',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20), nullable=True, comment='姓名'),
    sa.Column('gender', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='性别'),
    sa.Column('age', mysql.TINYINT(display_width=3), autoincrement=False, nullable=True, comment='年龄'),
    sa.Column('phone', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=11), nullable=True, comment='手机号码'),
    sa.Column('medical_history', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=1000), nullable=True, comment='既往病史'),
    sa.Column('height', mysql.FLOAT(precision=5, scale=2), nullable=True, comment='身高/cm'),
    sa.Column('weight', mysql.FLOAT(precision=5, scale=2), nullable=True, comment='体重/斤'),
    sa.Column('blood_pressure', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=True, comment='血压'),
    sa.Column('pulse', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True, comment='脉搏'),
    sa.Column('right_eye', mysql.FLOAT(precision=2, scale=1), nullable=True, comment='右眼视力'),
    sa.Column('left_eye', mysql.FLOAT(precision=2, scale=1), nullable=True, comment='左眼视力'),
    sa.Column('color_disc', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='辩色力'),
    sa.Column('hearing', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='听力'),
    sa.Column('facial_features', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='五官科'),
    sa.Column('internal_medicine', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='内科'),
    sa.Column('surgery', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='外科'),
    sa.Column('x_ray', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=50), nullable=True, comment='胸透'),
    sa.Column('created_time', mysql.DATETIME(), nullable=True, comment='插入时间'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('class_card',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='id'),
    sa.Column('school', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=30), server_default=sa.text("''"), nullable=False, comment='学校名'),
    sa.Column('class', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20), server_default=sa.text("''"), nullable=False, comment='班级名'),
    sa.Column('lecturer', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), server_default=sa.text("''"), nullable=False, comment='讲师'),
    sa.Column('num_sections', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), server_default=sa.text("''"), nullable=False, comment='节数'),
    sa.Column('start_time', mysql.TIME(), nullable=True, comment='开始时间'),
    sa.Column('end_time', mysql.TIME(), nullable=True, comment='结束时间'),
    sa.Column('school_year', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=15), server_default=sa.text("''"), nullable=False, comment='学年'),
    sa.PrimaryKeyConstraint('id'),
    comment='课程表',
    mysql_comment='课程表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('contacts',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20), server_default=sa.text("''"), nullable=False, comment='姓名'),
    sa.Column('mobile', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=11), server_default=sa.text("''"), nullable=False, comment='手机号码'),
    sa.Column('operator', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), server_default=sa.text("''"), nullable=False, comment='运营商'),
    sa.Column('attribution', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), server_default=sa.text("''"), nullable=False, comment='号码归属地'),
    sa.Column('status', mysql.TINYINT(display_width=2), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态,0失效,1有效'),
    sa.Column('comment', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=200), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_table('teachers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='id'),
    sa.Column('tea_num', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True, comment='编号'),
    sa.Column('name', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True, comment='姓名'),
    sa.Column('gender', mysql.ENUM('男', '女'), nullable=True, comment='性别'),
    sa.Column('phone', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=11), nullable=True, comment='手机号码'),
    sa.Column('email', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=20), nullable=True, comment='邮箱'),
    sa.Column('updated_time', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('created_time', mysql.DATETIME(), nullable=True, comment='插入时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('tea_num', 'teachers', ['tea_num'], unique=False)
    op.create_table('students',
    sa.Column('uid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='id'),
    sa.Column('stu_num', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=15), nullable=True, comment='学号'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=10), nullable=False, comment='姓名'),
    sa.Column('grade', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=4), nullable=True, comment='年级'),
    sa.Column('gender', mysql.ENUM('男', '女', '保密'), server_default=sa.text("'保密'"), nullable=True, comment='性别'),
    sa.Column('age', mysql.TINYINT(display_width=3), autoincrement=False, nullable=True, comment='年龄'),
    sa.Column('birth', sa.DATE(), nullable=True, comment='出生日期'),
    sa.Column('major', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='专业id'),
    sa.Column('class', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='班级id'),
    sa.Column('people_id', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=18), nullable=True, comment='身份证号码'),
    sa.Column('adm_date', sa.DATE(), nullable=True),
    sa.Column('nation', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=5), nullable=True, comment='民族'),
    sa.Column('tel', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=11), nullable=False, comment='手机号码'),
    sa.Column('address', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True, comment='家庭地址'),
    sa.Column('politics', mysql.ENUM('团员', '群众', '共产党员'), nullable=True, comment='政治面貌'),
    sa.Column('native_place', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20), nullable=True, comment='籍贯'),
    sa.Column('dorm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('registered_residence', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100), nullable=True, comment='户籍地'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    op.create_index('stu_num', 'students', ['stu_num'], unique=False)
    op.create_table('college',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=20), nullable=True, comment='学院名称'),
    sa.Column('campus_position', mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=8), nullable=False, comment='校区名称'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB',
    mysql_row_format='COMPACT'
    )
    # ### end Alembic commands ###
